-- V1 - Initial migration for the database

CREATE TABLE IF NOT EXISTS auth_users(
    id BIGSERIAL PRIMARY KEY,
    login VARCHAR(255) NOT NULL UNIQUE,
    password TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS hub_players(
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    contact VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS hub_places(
    id BIGSERIAL PRIMARY KEY,
    address TEXT NOT NULL,
    city VARCHAR(255) NOT NULL,
    cep VARCHAR(16) NOT NULL,
    status BOOLEAN NOT NULL DEFAULT TRUE,
    kind VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS hub_sports(
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    status BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS hub_activities(
    id BIGSERIAL PRIMARY KEY,
    date TIMESTAMP NOT NULL,
    info TEXT,
    place_id INT NOT NULL,
    sport_id INT NOT NULL,
    player_id INT NOT NULL,
    status BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (place_id) REFERENCES hub_places(id),
    FOREIGN KEY (sport_id) REFERENCES hub_sports(id),
    FOREIGN KEY (player_id) REFERENCES hub_players(id)
);