-- V1 - initialize_database.sql

CREATE TABLE IF NOT EXISTS auth_users(
    id SERIAL PRIMARY KEY,
    login VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(512) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS hub_players(
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    contact VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS hub_places(
    id SERIAL PRIMARY KEY,
    address VARCHAR(512) NOT NULL,
    city VARCHAR(255) NOT NULL,
    cep VARCHAR(16) NOT NULL,
    status BOOLEAN NOT NULL DEFAULT TRUE,
    kind VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS hub_sports(
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(512) NOT NULL,
    status BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS hub_activities(
    id SERIAL PRIMARY KEY,
    date TIMESTAMP NOT NULL,
    info VARCHAR(512) NOT NULL,
    place_id INT NOT NULL,
    sport_id INT NOT NULL,
    player_id INT NOT NULL,
    status BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (place_id) REFERENCES hub_places(id),
    FOREIGN KEY (sport_id) REFERENCES hub_sports(id),
    FOREIGN KEY (player_id) REFERENCES hub_players(id)
);

CREATE TABLE IF NOT EXISTS hub_activity_members(
    id SERIAL PRIMARY KEY,
    activity_id INT NOT NULL,
    player_id INT NOT NULL,
    status BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (activity_id) REFERENCES hub_activities(id),
    FOREIGN KEY (player_id) REFERENCES hub_players(id)
);